# Generated by Django 5.1.2 on 2024-12-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=200)),
                ("cnh", models.CharField(blank=True, max_length=20, null=True)),
                ("telefone", models.CharField(max_length=25)),
                ("tem_carro", models.BooleanField(default=False)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("senha", models.CharField(max_length=128)),
                ("nome_usuario", models.CharField(max_length=100, unique=True)),
                (
                    "tipo_usuario",
                    models.CharField(
                        choices=[("M", "Motorista"), ("P", "passageiro")], max_length=1
                    ),
                ),
            ],
        ),
    ]
