# Generated by Django 5.1.2 on 2024-12-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cidade", models.CharField(max_length=255)),
                ("estado", models.CharField(max_length=2)),
                ("rua", models.CharField(max_length=255)),
                ("numero", models.IntegerField()),
                ("bairro", models.CharField(max_length=255)),
            ],
        ),
    ]
