# Generated by Django 5.1.2 on 2024-12-08 20:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("endereco", "0001_initial"),
        ("perfil", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("horario", models.TimeField()),
                ("data", models.DateField(default=django.utils.timezone.now)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="ativo",
                        max_length=10,
                    ),
                ),
                (
                    "endereco_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caronas_destino",
                        to="endereco.endereco",
                    ),
                ),
                (
                    "endereco_saida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caronas_saida",
                        to="endereco.endereco",
                    ),
                ),
                (
                    "motorista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caronas_oferecidas",
                        to="perfil.usuario",
                    ),
                ),
                (
                    "passageiros",
                    models.ManyToManyField(
                        related_name="caronas_pegas", to="perfil.usuario"
                    ),
                ),
            ],
        ),
    ]
