# Generated by Django 5.1.2 on 2024-12-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carona',
            name='status',
            field=models.CharField(choices=[('A', 'Aberto'), ('F', 'Concluído'), ('C', 'Cancelado')], default='A', max_length=1),
        ),
    ]
